import { env } from "../config/env.js";

export const sendReportEmail = async ({ to, reportTitle, reportContent, format }) => {
  if (!env.email.resendApiKey) return; // Email not configured — silently skip

  const textPreview = (reportContent || "").slice(0, 500);
  const body = `
    <div style="font-family:sans-serif;max-width:600px;margin:0 auto;color:#111">
      <div style="background:#000;padding:24px 32px;border-radius:12px 12px 0 0">
        <p style="color:#00c853;font-size:12px;letter-spacing:2px;margin:0;text-transform:uppercase">Reportude AI</p>
        <h1 style="color:#fff;font-size:22px;margin:8px 0 0">${reportTitle}</h1>
      </div>
      <div style="background:#0d0d0d;border:1px solid #1e1e1e;border-top:none;padding:24px 32px;border-radius:0 0 12px 12px">
        <p style="color:#888;font-size:13px;margin:0 0 16px">Your report is ready.</p>
        <div style="background:#111;border:1px solid #1e1e1e;border-radius:8px;padding:16px;font-size:13px;color:#ccc;white-space:pre-wrap;line-height:1.6">
${textPreview}${reportContent?.length > 500 ? "\n\n…(truncated — log in to see full report)" : ""}
        </div>
        <p style="color:#444;font-size:11px;margin:20px 0 0">
          Format: ${format} · Generated by Reportude AI
        </p>
      </div>
    </div>
  `;

  await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${env.email.resendApiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      from: env.email.fromAddress,
      to: Array.isArray(to) ? to : [to],
      subject: `Report ready: ${reportTitle}`,
      html: body,
    }),
  });
};
